baseURL = "http://localhost:1313"
languageCode = "en"
DefaultContentLanguage = "en"
title = "PwnL0rd's Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm PwnL0rd"
author = "PwnL0rd"
description = "Call me PwnL0rd"
profilePicture = "img/main/sam.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/samsbp/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/samsbp"

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/pwnl0rd"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:mail@samsbp18@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
